

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: build 
  namespace: argocd
  labels:
    name: build
spec:
  project: default
  source:
    repoURL: https://github.com/vasudevas9030/build.git
    targetRevision: lab 
    path: Deployment
  destination:
    server: https://kubernetes.default.svc
    namespace: build
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true

